### ISSUE TITLE
Map doesn't appear

### ISSUE THREAD

**Issue by Gregivy** [eclipsesource/tabris-maps-example#1]
I have forked your project and did everything what was in readme, but map has not appeared.
![image](https://cloud.githubusercontent.com/assets/11299746/9850477/8564bb22-5afb-11e5-8c55-3c82799c25e5.png)

**Comment by jonek** [comment]
Hi @Gregivy thanks for checking out the example.
It seems that you have a problem with you maps API key.
We observed the same effect during development of the example and plugin several times and the API key was always the problem.
How are you building the example? Local build (i.e. Pro account) or Tabris.js build service?

**Comment by Gregivy** [comment]
Thank you for your response, I am using build service.

**Comment by jonek** [comment]
Ok.
1. Have you provided your API key in the environment variable?
2. Which SHA1 (for which signing key, a debug or a release key) did you use with you maps API key in  the Google developer console?
3. Did you build your app with the "debug" switch set to on or off? (The switch in the "settings" tab of your build.)

**Comment by Gregivy** [comment]
1. Yes, I put API_KEY_FOR_ANDROID in the first cell and key itself in the second one.
2. I used a debug key, did the same as in the instruction https://developers.google.com/maps/documentation/android-api/signup
3. I build with debug set to on

**Comment by jonek** [comment]
Ok. You have two possibilities:
1. Continue using a debug build. In that case our build service generates an internal debug key. For now you have no other possibility to get to the SHA1 of that key other than connecting to your Android device with `adb` and looking for something like this:

```
I/b       (16793): Sending API token request.
D/map.holder(16793): map is ready
I/System.out(16793): set: Properties [properties={zoom=13, center=[-33.867, 151.206]}]
I/System.out(16793): zoom to: 13.0
I/System.out(16793): move to: lat/lng: (-33.867,151.206)
E/b       (16793): Authentication failed on the server.
E/Google Maps Android API(16793): Authorization failure.  Please see https://developers.google.com/maps/documentation/android/start for how to correctly set up the map.
E/Google Maps Android API(16793): In the Google Developer Console (https://console.developers.google.com)
E/Google Maps Android API(16793): Ensure that the "Google Maps Android API v2"is enabled.
E/Google Maps Android API(16793): Ensure that the following Android Key exists:
E/Google Maps Android API(16793):   API Key: XXX-your-key-here-XXX
E/Google Maps Android API(16793):   Android Application (<cert_fingerprint>;<package_name>): YYY-SHA1-here-YYY;com.eclipsesource.tabris.maps.example
```

Then use the SHA1 from that output (where I put the `YYY-SHA1-here-YYY`) with your maps API key in the Google developer console.
We are going to improve our build service to make it easier to get the SHA1 of the internal debug key or to let users provide their own debug key.
2. Use a release signing key to build your app and switch off the debug button. Use the SHA1 of your own release key to create the maps API key.

Please report back and let me know when things work out. Thank you.

**Comment by jonek** [comment]
You will get the adb output mentioned above when you start your tabris-maps app (built with debug mode on!) on your Android device.

**Comment by Gregivy** [comment]
I tried the first method and did not succeed, I changed the sha1 in google dev console with the sha1 I found in the adb output. After the failure I tried to rebuild the app with new updated api key from google, but the result was the same.

**Comment by jonek** [comment]
Internally our build service creates a new debug key for every build. So rebuilding will change the SHA1 as a new debug key was generated.
Please try to update your existing API key with the SHA1 of your latest build. Do not generate a new API key. Then just restart your app. No need to rebuild or redeploy.
Also keep in mind that it sometimes takes a few minutes until the SHA1 fingerprints associated with a specific API key are updated on Google's side.

**Comment by Gregivy** [comment]
Just did it, yeah it works now, took about 4 minutes to associate the new key with new sha1, thank you very much!

**Comment by jonek** [comment]
Nice! If you have specific requirements not currently satisfied by the current tabris-maps custom widget, please open a new issue.
